import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

interface Info {
  data: {
    name: string
  }
}

interface Name {
  name: string

}

const Home: NextPage<Info> = (props) => {
  const [data, setData] = useState<Name>({name: 'Ellie D.'})
  console.log(props)
  console.log(data)

  const getIt = () => {
    fetch('api/hello')
      .then((res) => res.json())
      .then((data: Name) => {
        console.log("Got it?", data)
        setData(data)
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Oauth assignment using Gitlab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the GitLab Profiler!
        </h1>
        <p>{props.data.name}</p>
        <p>{data?.name ? data.name : ''}</p>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Login &rarr;</h2>
          </a>
        </div>
        <div onClick={getIt} className={styles.grid}>
          <a className={styles.card}>
            <h2>Client fetch &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}


export async function getServerSideProps(context: any) {
  const res = await fetch(`http://localhost:3000/api/hello`)
  const data: Info = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}

export default Home
